- hosts: all # see hosts.yaml file
  remote_user: root
  tasks:
    - name: deploy new vm
      proxmox:
	node: 'px1'
	api_user: root
	api_password: itescia
	api_host: px1
	password: itescia
	hostname: px1
	ostemplate: '/var/lib/vz/template/cache/debian-10.0-standard_10.0-1_amd64.tar.gz.tmp.78469'        
