- hosts: all # see hosts.yaml file
  remote_user: root
  tasks:
    - name: deploy new vm
      proxmox:
	node: 'uk-mc02'
	api_user: root
	api_password: itescia
	api_host: px1
	password: itescia
	hostname: px1
	ostemplate: 'local:vztmpl/debian-10.2.0-amd64-netinst.iso.tar.gz'
        
